Add:theme-macwen and theme-stack
halo-sigs/awesome-halo pull request #18
Opened 2023-01-02 10:42 UTC by jiewenhuang

添加主题[halo-theme-stack](https://github.com/jiewenhuang/halo-theme-stack)和[halo-theme-macwen](https://github.com/jiewenhuang/halo-theme-macwen)到主题>社区列表

2023-01-03 01:46 UTC, wan92hen requested changes

2023-01-03 01:46 UTC, wan92hen commented on README.md
> +- [theme-macwen](https://github.com/jiewenhuang/halo-theme-macwen) - 适用于Halo 2.0 的应用下载类主题
```suggestion
- [theme-macwen](https://github.com/jiewenhuang/halo-theme-macwen) - 适用于 Halo 2.0 的应用下载类主题
```

2023-01-03 01:46 UTC, wan92hen commented on README.md
> +- [theme-stack](https://github.com/jiewenhuang/halo-theme-stack) - 移植于[hugo-theme-stack](https://github.com/CaiJimmy/hugo-theme-stack)的个人博客主题
```suggestion
- [theme-stack](https://github.com/jiewenhuang/halo-theme-stack) - 移植于 [hugo-theme-stack](https://github.com/CaiJimmy/hugo-theme-stack) 的个人博客主题
```

2023-01-05 04:10 UTC, ruibaby reviewed
/lgtm

2023-01-05 08:36 UTC, JohnNiang approved these changes
/lgtm

2023-01-05 08:36 UTC, merged