add theme-ocean
halo-sigs/awesome-halo pull request #28
Opened 2023-02-22 14:22 UTC by lan-yonghui

添加 https://github.com/f2ccloud/theme-ocean 到社区主题列表。

```release-note
None
```

2023-02-22 15:00 UTC, ruibaby requested changes

2023-02-22 15:00 UTC, ruibaby commented on README.md
> +- [theme-ocean](https://github.com/f2ccloud/theme-ocean) - 适用于 Halo 2.0 的 知识库主题
```suggestion
- [theme-ocean](https://github.com/f2ccloud/theme-ocean) - 适用于 Halo 2.0 的 知识库类型主题
```

2023-02-23 01:58 UTC, lan-yonghui commented on README.md
> +- [theme-ocean](https://github.com/f2ccloud/theme-ocean) - 适用于 Halo 2.0 的 知识库主题
perfect

2023-02-23 02:04 UTC, wan92hen commented
/lgtm

2023-02-23 02:14 UTC, guqing reviewed
/lgtm

2023-02-23 02:33 UTC, ruibaby approved these changes
/approve

2023-02-23 02:34 UTC, merged