add halo-theme-aurora
halo-sigs/awesome-halo pull request #51
Opened 2023-08-13 14:31 UTC by Roozenlz

2023-08-13 15:06 UTC, ruibaby requested changes

2023-08-13 15:06 UTC, ruibaby commented on README.md
> +- [halo-theme-aurora](https://github.com/Roozenlz/halo-theme-aurora) - 移植自[hexo-theme-aurora](https://github.com/auroral-ui/hexo-theme-aurora)适配Halo2.x的Aurora主题
```suggestion
- [halo-theme-aurora](https://github.com/Roozenlz/halo-theme-aurora) - 移植自 [hexo-theme-aurora](https://github.com/auroral-ui/hexo-theme-aurora) 适配 Halo2.x 的 Aurora 主题
```

2023-08-13 15:19 UTC, ruibaby approved these changes
/approve

2023-08-14 02:59 UTC, guqing reviewed
/lgtm

2023-08-14 03:00 UTC, merged