chore: update some repos url
halo-sigs/awesome-halo pull request #54
Opened 2023-09-17 05:42 UTC by ruibaby

修改评论、搜索、RSS、Sitemap 插件的仓库地址。目前这四个插件已经转移到 halo-dev 组织。

/kind documentation

```release-note
None
```

2023-09-17 09:30 UTC, guqing reviewed
/approve

2023-09-19 06:44 UTC, JohnNiang requested changes

2023-09-19 06:44 UTC, JohnNiang commented on README.md
>  - [plugin-s3](https://github.com/halo-sigs/plugin-s3) - 为 Halo 2.0 提供 S3 协议的对象存储策略，支持阿里云、腾讯云、七牛云等兼容 S3 协议的厂商。
```suggestion
- [plugin-s3](https://github.com/halo-dev/plugin-s3) - 为 Halo 2.0 提供 S3 协议的对象存储策略，支持阿里云、腾讯云、七牛云等兼容 S3 协议的厂商。
```

2023-09-19 07:02 UTC, JohnNiang approved these changes
/lgtm

2023-09-19 07:04 UTC, merged