添加一个导出文章插件
halo-sigs/awesome-halo pull request #60
Opened 2023-11-13 06:28 UTC by Lyn4ever29

- 插件地址：
[halo-plugin-export-md](https://github.com/Lyn4ever29/halo-plugin-export-md)
- 功能：
导出文章为Markdown、Html文件并打包下载

2023-11-14 03:08 UTC, JohnNiang approved these changes
/approve

2023-11-14 03:09 UTC, JohnNiang commented
/retitle Add plugin halo-plugin-export-md

2023-11-14 03:14 UTC, ruibaby commented
/hold

2023-11-14 03:27 UTC, ruibaby commented
提几点建议：

1. UI：建议直接使用 `@halo-dev/components` 中的组件，不要引入 Element UI，比如下面的弹框，似乎可以直接使用 Dialog API，即便需要在这个弹框添加 UI，也可以使用 VModal 组件，如果组件有任何不满足，建议向 Halo 提交 issue 以改进。
	<img width="1665" alt="图片" src="https://github.com/halo-sigs/awesome-halo/assets/21301288/a57848d7-0aea-4c49-be8f-d09575d8c669">
2. 移除无用注释以及 console.log，比如：https://github.com/Lyn4ever29/halo-plugin-export-md/blob/03a02bf894dd04d35d68fef1a89c4ecada502705/console/src/views/HomeView.vue#L56-L63
3. 使用符合插件意义的图标和 Logo。
	
	<img width="331" alt="图片" src="https://github.com/halo-sigs/awesome-halo/assets/21301288/eda49e1e-d8c8-4d46-8d75-91d630ddb7a9">
	<img width="246" alt="图片" src="https://github.com/halo-sigs/awesome-halo/assets/21301288/5350a2f0-dc05-408b-99ee-26b49f52a966">
	<img width="394" alt="图片" src="https://github.com/halo-sigs/awesome-halo/assets/21301288/76c72b88-b471-4ac8-87d6-28ff79f4ede4">
4. 关于页面似乎不必要，建议写在仓库的 README 里面。
	<img width="398" alt="图片" src="https://github.com/halo-sigs/awesome-halo/assets/21301288/9eb58f81-18f6-48bb-8d12-7781c75cc70a">

2023-11-14 03:28 UTC, ruibaby requested changes

2023-11-14 03:28 UTC, ruibaby commented on README.md
> +- [halo-plugin-export-md](https://github.com/Lyn4ever29/halo-plugin-export-md) - 导出文章为Markdown、Html文件并打包下载
```suggestion
- [halo-plugin-export-md](https://github.com/Lyn4ever29/halo-plugin-export-md) - 导出文章为 Markdown、HTML 文件并打包下载
```

2023-11-20 12:01 UTC, ruibaby approved these changes
/lgtm

2023-11-20 12:02 UTC, ruibaby commented
晚些时候我会发布到应用市场。

2023-11-20 12:04 UTC, merged