add halo-plugin-meilisearch
halo-sigs/awesome-halo pull request #69
Opened 2024-01-12 16:53 UTC by Rainsheep

2024-01-12 16:55 UTC, Rainsheep commented
辛苦帮忙审批下，并发布到应用商店。

2024-01-13 01:24 UTC, ruibaby requested changes
感谢

2024-01-13 01:24 UTC, ruibaby commented on README.md
> +- [halo-plugin-meilisearch](https://github.com/Rainsheep/halo-plugin-meilisearch) - 为 Halo 2.0 提供更强大、更精确、更易用的搜索功能。
```suggestion
- [halo-plugin-meilisearch](https://github.com/Rainsheep/halo-plugin-meilisearch) - 集成 Meilisearch，为 Halo 2.0 提供更强大、更精确、更易用的搜索功能。
```

2024-01-13 01:30 UTC, ruibaby commented
感谢花时间为 Halo 开发插件，以下是一些改进建议：

1. https://github.com/Rainsheep/halo-plugin-meilisearch/blob/main/src/main/resources/plugin.yaml
    1. metadata.name 可以直接叫 meilisearch 或者 meilisearch-integration，因为 Kind 已经是 Plugin，没有必要再加 Plugin 前缀。
    2. logo 建议放在本地，可以将此图片下载到 resources 目录命名为 logo.svg，然后 logo 字段直接改为 logo.svg 即可。
    3. 插件显示名称建议直接叫 Meilisearch，或者 Meilisearch 集成，Meilisearch 属于产品名称，我们没有必要为其翻译。

2024-01-13 07:41 UTC, Rainsheep commented
@ruibaby 感谢建议，已按建议进行修改，请有空再帮 review

2024-01-13 07:42 UTC, ruibaby approved these changes
/lgtm

2024-01-13 07:43 UTC, ruibaby commented
> @ruibaby 感谢建议，已按建议进行修改，请有空再帮 review

我这里没啥问题了，先上架让大家体验吧。然后看看大家的反馈。

https://www.halo.run/store/apps/app-yJlEz

2024-01-13 07:44 UTC, merged