辛苦帮忙审批下，并发布到应用商店。
halo-sigs/awesome-halo pull request #81
Opened 2024-04-05 10:39 UTC by wenjing-xin

## 插件主要功能：
- 文章页链接加入安全跳转中台
- 自定义白名单
- 兼容链接管理插件的链接数据
- 自定义安全中台页面内容

2024-04-07 02:03 UTC, ruibaby requested changes
感谢 @wenjing-xin 为 Halo 生态添砖加瓦~

cc @halo-sigs/halo 

请帮忙简单 Review 一下。

2024-04-07 02:03 UTC, ruibaby commented on README.md
> +- [link-security-detect](https://github.com/wenjing-xin/link-security-detect) - Halo2.0 的安全条跳转中台插件，防止恶意链接直接跳转导致本站被搜索引擎拉黑的风险
```suggestion
- [link-security-detect](https://github.com/wenjing-xin/link-security-detect) - Halo 2.0 的安全条跳转中台插件，防止恶意链接直接跳转导致本站被搜索引擎拉黑的风险
```

2024-04-07 04:13 UTC, wenjing-xin commented on README.md
> +- [link-security-detect](https://github.com/wenjing-xin/link-security-detect) - Halo2.0 的安全条跳转中台插件，防止恶意链接直接跳转导致本站被搜索引擎拉黑的风险
是的 没问题，感谢！

2024-04-09 09:10 UTC, JohnNiang reviewed
这种功能如果用 JS 来做会不会更好呢

2024-04-26 00:11 UTC, wenjing-xin reviewed
仓库地址变更，我重新提交下在

2024-04-26 03:05 UTC, JohnNiang commented on README.md
> +- [link-security-detect](https://github.com/wenjing-xin/plugins-lins-security-detect) - Halo2.0 的安全条跳转中台插件，防止恶意链接直接跳转导致本站被搜索引擎拉黑的风险
我发现新修改的仓库已经没有插件源码了。请 @halo-sigs/halo 看看。

2024-04-26 09:50 UTC, wenjing-xin commented on README.md
> +- [link-security-detect](https://github.com/wenjing-xin/plugins-lins-security-detect) - Halo2.0 的安全条跳转中台插件，防止恶意链接直接跳转导致本站被搜索引擎拉黑的风险
目前插件不准备开放源码，可以加入到生态周边吗？

2024-04-28 02:03 UTC, ruibaby commented on README.md
> +- [link-security-detect](https://github.com/wenjing-xin/plugins-lins-security-detect) - Halo2.0 的安全条跳转中台插件，防止恶意链接直接跳转导致本站被搜索引擎拉黑的风险
可以加到 awesome-halo，但建议标注一下为闭源。应用市场也可以上架闭源的，但需要经过我们的代码 Review。

2024-04-28 02:47 UTC, wenjing-xin commented on README.md
> +- [link-security-detect](https://github.com/wenjing-xin/plugins-lins-security-detect) - Halo2.0 的安全条跳转中台插件，防止恶意链接直接跳转导致本站被搜索引擎拉黑的风险
嗯嗯 好滴，麻烦您提供一下您的邮箱，我把您拉入司有仓库，对代码进行审查

2024-04-28 09:26 UTC, ruibaby commented on README.md
> +- [link-security-detect](https://github.com/wenjing-xin/plugins-lins-security-detect) - Halo2.0 的安全条跳转中台插件，防止恶意链接直接跳转导致本站被搜索引擎拉黑的风险
hi @wenjing-xin ，我已经查看了代码，目前我们的决定是暂时不上架，原因如下：

我发现你的插件里自行实现了授权机制，我们认为这可能会给用户造成割裂的体验，毕竟我们目前也有官方的许可证校验机制。

当然，这和我们也有一定的关系，目前 Halo 应用市场暂时还没有明文的上架规范，也还未支持开发者入驻。所以我们期望后续完善相关机制之后能够和开发者达成一致的观点。

希望能够理解。

2024-04-28 10:01 UTC, wenjing-xin commented on README.md
> +- [link-security-detect](https://github.com/wenjing-xin/plugins-lins-security-detect) - Halo2.0 的安全条跳转中台插件，防止恶意链接直接跳转导致本站被搜索引擎拉黑的风险
> hi @wenjing-xin ，我已经查看了代码，目前我们的决定是暂时不上架，原因如下：
> 
> 我发现你的插件里自行实现了授权机制，我们认为这可能会给用户造成割裂的体验，毕竟我们目前也有官方的许可证校验机制。
> 
> 当然，这和我们也有一定的关系，目前 Halo 应用市场暂时还没有明文的上架规范，也还未支持开发者入驻。所以我们期望后续完善相关机制之后能够和开发者达成一致的观点。
> 
> 希望能够理解。

好的，麻烦可以加入到周边生态里边吗？

2024-04-29 02:49 UTC, ruibaby commented on README.md
> +- [link-security-detect](https://github.com/wenjing-xin/plugins-lins-security-detect) - Halo2.0 的安全条跳转中台插件，防止恶意链接直接跳转导致本站被搜索引擎拉黑的风险
处理一下冲突吧，现在有一个冲突。

2024-04-29 02:59 UTC, wenjing-xin commented on README.md
> +- [link-security-detect](https://github.com/wenjing-xin/plugins-lins-security-detect) - Halo2.0 的安全条跳转中台插件，防止恶意链接直接跳转导致本站被搜索引擎拉黑的风险
> 处理一下冲突吧，现在有一个冲突。
已处理

2024-04-29 02:59 UTC, ruibaby approved these changes
/approve

2024-04-29 03:08 UTC, JohnNiang commented on README.md
> +- [Plugin-link-security-detect](https://github.com/wenjing-xin/plugins-links-security-detect) - Halo2.0 的安全条跳转中台插件，防止恶意链接直接跳转导致本站被搜索引擎拉黑的风险
```suggestion
- [plugin-link-security-detect](https://github.com/wenjing-xin/plugins-links-security-detect) - Halo 2.0 的安全条跳转中台插件，防止恶意链接直接跳转导致本站被搜索引擎拉黑的风险。
```

2024-04-29 03:19 UTC, JohnNiang approved these changes
/lgtm

2024-04-29 03:27 UTC, merged