新增主题 halo-theme-fresh
halo-sigs/awesome-halo pull request #92
Opened 2024-05-20 09:26 UTC by adozhao

2024-05-20 16:34 UTC, JohnNiang requested changes

2024-05-20 16:34 UTC, JohnNiang commented on README.md
> +- [halo-theme-zero](https://github.com/adozhao/halo-theme-fresh) - 一款清新的 Halo 2.0 主题
```suggestion
- [halo-theme-fresh](https://github.com/adozhao/halo-theme-fresh) - 一款清新的 Halo 2.0 主题
```

2024-05-21 02:11 UTC, JohnNiang approved these changes
Thanks for your contribution!

/approve

2024-05-21 02:13 UTC, ruibaby approved these changes
/lgtm

2024-05-21 02:14 UTC, merged

2024-05-21 02:18 UTC, ruibaby commented
https://www.halo.run/store/apps/app-owNyx